// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gwkeitdb

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.findSnippetsByTagsStmt, err = db.PrepareContext(ctx, findSnippetsByTags); err != nil {
		return nil, fmt.Errorf("error preparing query FindSnippetsByTags: %w", err)
	}
	if q.findTagsBySnippetIdStmt, err = db.PrepareContext(ctx, findTagsBySnippetId); err != nil {
		return nil, fmt.Errorf("error preparing query FindTagsBySnippetId: %w", err)
	}
	if q.findTagsByTagStmt, err = db.PrepareContext(ctx, findTagsByTag); err != nil {
		return nil, fmt.Errorf("error preparing query FindTagsByTag: %w", err)
	}
	if q.findUrlsBySnippetIdStmt, err = db.PrepareContext(ctx, findUrlsBySnippetId); err != nil {
		return nil, fmt.Errorf("error preparing query FindUrlsBySnippetId: %w", err)
	}
	if q.getSnippetCountStmt, err = db.PrepareContext(ctx, getSnippetCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetSnippetCount: %w", err)
	}
	if q.getSnippetsStmt, err = db.PrepareContext(ctx, getSnippets); err != nil {
		return nil, fmt.Errorf("error preparing query GetSnippets: %w", err)
	}
	if q.insertSnippetStmt, err = db.PrepareContext(ctx, insertSnippet); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSnippet: %w", err)
	}
	if q.insertSnippetTagStmt, err = db.PrepareContext(ctx, insertSnippetTag); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSnippetTag: %w", err)
	}
	if q.insertTagStmt, err = db.PrepareContext(ctx, insertTag); err != nil {
		return nil, fmt.Errorf("error preparing query InsertTag: %w", err)
	}
	if q.insertUrlStmt, err = db.PrepareContext(ctx, insertUrl); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUrl: %w", err)
	}
	if q.insertUrlSnippetStmt, err = db.PrepareContext(ctx, insertUrlSnippet); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUrlSnippet: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.findSnippetsByTagsStmt != nil {
		if cerr := q.findSnippetsByTagsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findSnippetsByTagsStmt: %w", cerr)
		}
	}
	if q.findTagsBySnippetIdStmt != nil {
		if cerr := q.findTagsBySnippetIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findTagsBySnippetIdStmt: %w", cerr)
		}
	}
	if q.findTagsByTagStmt != nil {
		if cerr := q.findTagsByTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findTagsByTagStmt: %w", cerr)
		}
	}
	if q.findUrlsBySnippetIdStmt != nil {
		if cerr := q.findUrlsBySnippetIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findUrlsBySnippetIdStmt: %w", cerr)
		}
	}
	if q.getSnippetCountStmt != nil {
		if cerr := q.getSnippetCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSnippetCountStmt: %w", cerr)
		}
	}
	if q.getSnippetsStmt != nil {
		if cerr := q.getSnippetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSnippetsStmt: %w", cerr)
		}
	}
	if q.insertSnippetStmt != nil {
		if cerr := q.insertSnippetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSnippetStmt: %w", cerr)
		}
	}
	if q.insertSnippetTagStmt != nil {
		if cerr := q.insertSnippetTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSnippetTagStmt: %w", cerr)
		}
	}
	if q.insertTagStmt != nil {
		if cerr := q.insertTagStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertTagStmt: %w", cerr)
		}
	}
	if q.insertUrlStmt != nil {
		if cerr := q.insertUrlStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUrlStmt: %w", cerr)
		}
	}
	if q.insertUrlSnippetStmt != nil {
		if cerr := q.insertUrlSnippetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUrlSnippetStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                      DBTX
	tx                      *sql.Tx
	findSnippetsByTagsStmt  *sql.Stmt
	findTagsBySnippetIdStmt *sql.Stmt
	findTagsByTagStmt       *sql.Stmt
	findUrlsBySnippetIdStmt *sql.Stmt
	getSnippetCountStmt     *sql.Stmt
	getSnippetsStmt         *sql.Stmt
	insertSnippetStmt       *sql.Stmt
	insertSnippetTagStmt    *sql.Stmt
	insertTagStmt           *sql.Stmt
	insertUrlStmt           *sql.Stmt
	insertUrlSnippetStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                      tx,
		tx:                      tx,
		findSnippetsByTagsStmt:  q.findSnippetsByTagsStmt,
		findTagsBySnippetIdStmt: q.findTagsBySnippetIdStmt,
		findTagsByTagStmt:       q.findTagsByTagStmt,
		findUrlsBySnippetIdStmt: q.findUrlsBySnippetIdStmt,
		getSnippetCountStmt:     q.getSnippetCountStmt,
		getSnippetsStmt:         q.getSnippetsStmt,
		insertSnippetStmt:       q.insertSnippetStmt,
		insertSnippetTagStmt:    q.insertSnippetTagStmt,
		insertTagStmt:           q.insertTagStmt,
		insertUrlStmt:           q.insertUrlStmt,
		insertUrlSnippetStmt:    q.insertUrlSnippetStmt,
	}
}
