// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gwkeitdb

type Snippet struct {
	ID    int64
	Title string
	Body  string
}

type SnippetsTag struct {
	ID        int64
	SnippetID int64
	TagID     int64
}

type Tag struct {
	ID  int64
	Tag string
}

type Url struct {
	ID        int64
	Url       string
	SnippetID int64
}
