// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gwkeitdb

import (
	"database/sql"
)

type Snippet struct {
	ID          int64
	Title       string
	Body        string
	Description string
	Url         string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type SnippetsFt struct {
	Title       string
	Body        string
	Description string
	Url         string
}

type SnippetsTag struct {
	ID        int64
	SnippetID int64
	TagID     int64
}

type Tag struct {
	ID  int64
	Tag string
}

type Url struct {
	ID        int64
	Url       string
	SnippetID int64
}
