// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package gwkeitdb

import (
	"context"
	"strings"
)

const findSnippetsByTags = `-- name: FindSnippetsByTags :many
SELECT s.id, s.title, s.body
FROM snippets s
JOIN snippets_tags st on s.id = st.snippet_id
JOIN tags t on st.tag_id = t.id
WHERE t.tag IN (/*SLICE:tags*/?)
`

func (q *Queries) FindSnippetsByTags(ctx context.Context, tags []string) ([]Snippet, error) {
	query := findSnippetsByTags
	var queryParams []interface{}
	if len(tags) > 0 {
		for _, v := range tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snippet
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(&i.ID, &i.Title, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTagsBySnippetId = `-- name: FindTagsBySnippetId :many
SELECT t.id, t.tag
FROM tags t
JOIN snippets_tags st on t.id = st.tag_id
WHERE st.snippet_id = ?
`

func (q *Queries) FindTagsBySnippetId(ctx context.Context, snippetID int64) ([]Tag, error) {
	rows, err := q.query(ctx, q.findTagsBySnippetIdStmt, findTagsBySnippetId, snippetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTagsByTag = `-- name: FindTagsByTag :many
SELECT id, tag FROM tags WHERE tag IN (/*SLICE:tags*/?)
`

func (q *Queries) FindTagsByTag(ctx context.Context, tags []string) ([]Tag, error) {
	query := findTagsByTag
	var queryParams []interface{}
	if len(tags) > 0 {
		for _, v := range tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUrlsBySnippetId = `-- name: FindUrlsBySnippetId :many
SELECT u.id, u.url
FROM urls u
JOIN snippets_urls su on u.id = su.url_id
WHERE su.snippet_id = ?
`

func (q *Queries) FindUrlsBySnippetId(ctx context.Context, snippetID int64) ([]Url, error) {
	rows, err := q.query(ctx, q.findUrlsBySnippetIdStmt, findUrlsBySnippetId, snippetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnippetCount = `-- name: GetSnippetCount :one
SELECT COUNT(*) FROM snippets
`

func (q *Queries) GetSnippetCount(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getSnippetCountStmt, getSnippetCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSnippets = `-- name: GetSnippets :many
SELECT id, title, body FROM snippets
`

func (q *Queries) GetSnippets(ctx context.Context) ([]Snippet, error) {
	rows, err := q.query(ctx, q.getSnippetsStmt, getSnippets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snippet
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(&i.ID, &i.Title, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSnippet = `-- name: InsertSnippet :one
INSERT INTO snippets (title, body) VALUES (?, ?) RETURNING id
`

type InsertSnippetParams struct {
	Title string
	Body  string
}

func (q *Queries) InsertSnippet(ctx context.Context, arg InsertSnippetParams) (int64, error) {
	row := q.queryRow(ctx, q.insertSnippetStmt, insertSnippet, arg.Title, arg.Body)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSnippetTag = `-- name: InsertSnippetTag :exec
INSERT INTO snippets_tags (snippet_id, tag_id) VALUES (?, ?)
`

type InsertSnippetTagParams struct {
	SnippetID int64
	TagID     int64
}

func (q *Queries) InsertSnippetTag(ctx context.Context, arg InsertSnippetTagParams) error {
	_, err := q.exec(ctx, q.insertSnippetTagStmt, insertSnippetTag, arg.SnippetID, arg.TagID)
	return err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (tag) VALUES (?) RETURNING id
`

func (q *Queries) InsertTag(ctx context.Context, tag string) (int64, error) {
	row := q.queryRow(ctx, q.insertTagStmt, insertTag, tag)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertUrl = `-- name: InsertUrl :one
INSERT INTO urls (url) VALUES (?) RETURNING id
`

func (q *Queries) InsertUrl(ctx context.Context, url string) (int64, error) {
	row := q.queryRow(ctx, q.insertUrlStmt, insertUrl, url)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertUrlSnippet = `-- name: InsertUrlSnippet :exec
INSERT INTO snippets_urls (url_id, snippet_id) VALUES (?, ?)
`

type InsertUrlSnippetParams struct {
	UrlID     int64
	SnippetID int64
}

func (q *Queries) InsertUrlSnippet(ctx context.Context, arg InsertUrlSnippetParams) error {
	_, err := q.exec(ctx, q.insertUrlSnippetStmt, insertUrlSnippet, arg.UrlID, arg.SnippetID)
	return err
}
