// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package gwkeitdb

import (
	"context"
	"database/sql"
	"strings"
)

const deleteSnippetTags = `-- name: DeleteSnippetTags :exec
DELETE FROM snippets_tags
WHERE id IN (
    SELECT st.id
    FROM snippets_tags st
    LEFT JOIN tags ON snippets_tags.tag_id = tags.id
    WHERE snippets_tags.tag_id IN (/*SLICE:tagIds*/?) AND snippets_tags.snippet_id = ?
)
`

type DeleteSnippetTagsParams struct {
	TagIds    []int64
	SnippetID int64
}

func (q *Queries) DeleteSnippetTags(ctx context.Context, arg DeleteSnippetTagsParams) error {
	query := deleteSnippetTags
	var queryParams []interface{}
	if len(arg.TagIds) > 0 {
		for _, v := range arg.TagIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tagIds*/?", strings.Repeat(",?", len(arg.TagIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tagIds*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.SnippetID)
	_, err := q.exec(ctx, nil, query, queryParams...)
	return err
}

const deleteSnippetUrls = `-- name: DeleteSnippetUrls :exec
DELETE FROM urls WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteSnippetUrls(ctx context.Context, ids []int64) error {
	query := deleteSnippetUrls
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.exec(ctx, nil, query, queryParams...)
	return err
}

const deleteTagByTag = `-- name: DeleteTagByTag :exec
DELETE FROM tags WHERE tag = ?
`

func (q *Queries) DeleteTagByTag(ctx context.Context, tag string) error {
	_, err := q.exec(ctx, q.deleteTagByTagStmt, deleteTagByTag, tag)
	return err
}

const findSnippetDataById = `-- name: FindSnippetDataById :one
SELECT s.id, s.title, s.body, s.description, s.url, s.created_at, s.updated_at, group_concat(COALESCE(t.tag, ''), ' ') as tag_list, group_concat(COALESCE(u.url, ''), ' ') as url_list
FROM snippets s
LEFT JOIN snippets_tags st ON s.id = st.snippet_id
LEFT JOIN tags t ON st.tag_id = t.id
LEFT JOIN urls u on s.id = u.snippet_id
WHERE s.id = ?
GROUP BY s.id
`

type FindSnippetDataByIdRow struct {
	ID          int64
	Title       string
	Body        string
	Description string
	Url         string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	TagList     string
	UrlList     string
}

func (q *Queries) FindSnippetDataById(ctx context.Context, id int64) (FindSnippetDataByIdRow, error) {
	row := q.queryRow(ctx, q.findSnippetDataByIdStmt, findSnippetDataById, id)
	var i FindSnippetDataByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Description,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TagList,
		&i.UrlList,
	)
	return i, err
}

const findSnippetsByLikeTags = `-- name: FindSnippetsByLikeTags :many
SELECT s.id, s.title, s.body, s.description, s.url, s.created_at, s.updated_at
FROM snippets s
JOIN snippets_tags st on s.id = st.snippet_id
JOIN tags t on st.tag_id = t.id
WHERE t.tag LIKE (?1)
`

func (q *Queries) FindSnippetsByLikeTags(ctx context.Context, tag string) ([]Snippet, error) {
	rows, err := q.query(ctx, q.findSnippetsByLikeTagsStmt, findSnippetsByLikeTags, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snippet
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Description,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSnippetsByTags = `-- name: FindSnippetsByTags :many
SELECT s.id, s.title, s.body, s.description, s.url, s.created_at, s.updated_at
FROM snippets s
JOIN snippets_tags st on s.id = st.snippet_id
JOIN tags t on st.tag_id = t.id
WHERE t.tag IN (/*SLICE:tags*/?)
`

func (q *Queries) FindSnippetsByTags(ctx context.Context, tags []string) ([]Snippet, error) {
	query := findSnippetsByTags
	var queryParams []interface{}
	if len(tags) > 0 {
		for _, v := range tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snippet
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Description,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSnippetsPaginated = `-- name: FindSnippetsPaginated :many
SELECT s.id, s.title, s.body, s.description, s.url, s.created_at, s.updated_at
FROM snippets s
ORDER BY s.created_at DESC
LIMIT ?
OFFSET ?
`

type FindSnippetsPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) FindSnippetsPaginated(ctx context.Context, arg FindSnippetsPaginatedParams) ([]Snippet, error) {
	rows, err := q.query(ctx, q.findSnippetsPaginatedStmt, findSnippetsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snippet
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Description,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTagsBySnippetId = `-- name: FindTagsBySnippetId :many
SELECT t.id, t.tag
FROM tags t
JOIN snippets_tags st on t.id = st.tag_id
WHERE st.snippet_id = ?
`

func (q *Queries) FindTagsBySnippetId(ctx context.Context, snippetID int64) ([]Tag, error) {
	rows, err := q.query(ctx, q.findTagsBySnippetIdStmt, findTagsBySnippetId, snippetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTagsByTag = `-- name: FindTagsByTag :many
SELECT id, tag FROM tags WHERE tag IN (/*SLICE:tags*/?)
`

func (q *Queries) FindTagsByTag(ctx context.Context, tags []string) ([]Tag, error) {
	query := findTagsByTag
	var queryParams []interface{}
	if len(tags) > 0 {
		for _, v := range tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	rows, err := q.query(ctx, nil, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUrlsBySnippetId = `-- name: FindUrlsBySnippetId :many
SELECT u.id, u.url, u.snippet_id
FROM urls u
WHERE u.snippet_id = ?
`

func (q *Queries) FindUrlsBySnippetId(ctx context.Context, snippetID int64) ([]Url, error) {
	rows, err := q.query(ctx, q.findUrlsBySnippetIdStmt, findUrlsBySnippetId, snippetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(&i.ID, &i.Url, &i.SnippetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSnippetCount = `-- name: GetSnippetCount :one
SELECT COUNT(*) FROM snippets
`

func (q *Queries) GetSnippetCount(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getSnippetCountStmt, getSnippetCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSnippet = `-- name: InsertSnippet :one
INSERT INTO snippets (title, body, description, url) VALUES (?, ?, ?, ?) RETURNING id
`

type InsertSnippetParams struct {
	Title       string
	Body        string
	Description string
	Url         string
}

func (q *Queries) InsertSnippet(ctx context.Context, arg InsertSnippetParams) (int64, error) {
	row := q.queryRow(ctx, q.insertSnippetStmt, insertSnippet,
		arg.Title,
		arg.Body,
		arg.Description,
		arg.Url,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSnippetTag = `-- name: InsertSnippetTag :exec
INSERT INTO snippets_tags (snippet_id, tag_id) VALUES (?, ?)
`

type InsertSnippetTagParams struct {
	SnippetID int64
	TagID     int64
}

func (q *Queries) InsertSnippetTag(ctx context.Context, arg InsertSnippetTagParams) error {
	_, err := q.exec(ctx, q.insertSnippetTagStmt, insertSnippetTag, arg.SnippetID, arg.TagID)
	return err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (tag) VALUES (?) RETURNING id
`

func (q *Queries) InsertTag(ctx context.Context, tag string) (int64, error) {
	row := q.queryRow(ctx, q.insertTagStmt, insertTag, tag)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertUrl = `-- name: InsertUrl :one
INSERT INTO urls (url, snippet_id) VALUES (?, ?) RETURNING id
`

type InsertUrlParams struct {
	Url       string
	SnippetID int64
}

func (q *Queries) InsertUrl(ctx context.Context, arg InsertUrlParams) (int64, error) {
	row := q.queryRow(ctx, q.insertUrlStmt, insertUrl, arg.Url, arg.SnippetID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const snippetTagExists = `-- name: SnippetTagExists :one
SELECT EXISTS (SELECT 1 FROM snippets_tags JOIN tags ON snippets_tags.tag_id = tags.id WHERE tags.tag = ?)
`

func (q *Queries) SnippetTagExists(ctx context.Context, tag string) (int64, error) {
	row := q.queryRow(ctx, q.snippetTagExistsStmt, snippetTagExists, tag)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSnippet = `-- name: UpdateSnippet :exec
UPDATE snippets SET title = ?, body = ?, description = ?, url = ?, updated_at = current_timestamp WHERE id = ?
`

type UpdateSnippetParams struct {
	Title       string
	Body        string
	Description string
	Url         string
	ID          int64
}

func (q *Queries) UpdateSnippet(ctx context.Context, arg UpdateSnippetParams) error {
	_, err := q.exec(ctx, q.updateSnippetStmt, updateSnippet,
		arg.Title,
		arg.Body,
		arg.Description,
		arg.Url,
		arg.ID,
	)
	return err
}
